services:
  iditarod:
    build: .
    container_name: iditarod
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/pupyrus:/opt/pupyrus:ro
      - /opt/pupyrus/html:/opt/pupyrus/html
      - runner-work:/home/runner/actions-runner/_work
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  runner-work:
