services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: soulseek-vpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=${SOULSEEK_TOKEN}
      - CONNECT=NETHERLANDS
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.86.0/24
    ports:
      - 6080:6080
      - 61122:61122
      - 61123:61123
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
  soulseek:
    image: realies/soulseek
    container_name: soulseek
    restart: unless-stopped
    volumes:
      - /opt/soulseek:/data/.SoulseekQt
      - /mammoth/downloads/soulseek:/data/Soulseek Downloads
      - /mammoth/library/music:/data/Soulseek Shared Folder
      - /opt/soulseek/logs:/data/Soulseek Chat Logs
    environment:
      - PGID=1003
      - PUID=988
    network_mode: service:vpn
    depends_on:
      - vpn