services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=America/Los_Angeles
    volumes:
      - /opt/radarr:/config
      - /mammoth/library/movies:/movies
      - /mammoth/downloads/transmission:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    network_mode: host