services:
  pawpcorn:
    container_name: pawpcorn
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    network_mode: host
    volumes:
      - /opt/pawpcorn/config:/config
      - /mammoth/pawpcorn/transcode:/transcode
      - /mammoth/library/movies:/data/Movies
      - /mammoth/library/tv:/data/TV
      - /mammoth/library/music:/data/Music
      - /mammoth/library/videos:/data/Videos
      - /mammoth/library/stand-up:/data/Stand Up
    devices:
      - /dev/dri:/dev/dri