services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1003
      - PGID=1003
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true
    volumes:
      - /opt/jackett:/config
      - /mammoth/downloads/transmission:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped