services:
  telstr:
    image: henrygd/beszel
    container_name: telstr
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /opt/telstr/data:/beszel_data
      - /opt/telstr/socket:/beszel_socket
    networks:
      - loft-proxy

networks:
  loft-proxy:
    external: true