services:
  snoot:
    image: henrygd/beszel-agent
    container_name: snoot
    restart: unless-stopped
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: "45876"
      KEY: "${BESZEL_KEY}"
      TOKEN: "${BESZEL_TOKEN}"
