general = {
  name = "The Loft";
  output_backend = "pipe";
};
pipe = {
  name = "/tmp/snapcast/shairport-fifo";
  audio_backend_buffer_desired_length_in_seconds = 0.0;
  output_format = "S16_LE";
  output_rate = 44100;
};
