[http]
enabled = true
bind_address = 0.0.0.0
port = 1780
doc_root = /usr/share/snapserver/snapweb

[stream]
source = pipe:///tmp/snapcast/shairport-fifo?name=AirPlay&sampleformat=44100:16:2&mode=create
source = pipe:///tmp/snapcast/spotify-fifo?name=Spotify&sampleformat=44100:16:2&mode=create
