services:
  beacn:
    image: louislam/uptime-kuma:1
    container_name: beacn
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /opt/beacn/data:/app/data
    networks:
      - loft-proxy

networks:
  loft-proxy:
    external: true
